// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl8NTzw1BXEr1PVIju6LSWvkribc00ppY',
    appId: '1:16690528086:web:8bacde546a458513da20f7',
    messagingSenderId: '16690528086',
    projectId: 'totelx',
    authDomain: 'totelx.firebaseapp.com',
    storageBucket: 'totelx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL3n_7bs9YXo_z7nvcP_SBPv_nWuB18CE',
    appId: '1:16690528086:android:6ffce9a54f753580da20f7',
    messagingSenderId: '16690528086',
    projectId: 'totelx',
    storageBucket: 'totelx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-gcXYltjl4P30rKqQ6L_kKmA2J5Z9rb0',
    appId: '1:16690528086:ios:2e79bec8bd9ea865da20f7',
    messagingSenderId: '16690528086',
    projectId: 'totelx',
    storageBucket: 'totelx.appspot.com',
    iosBundleId: 'com.example.totelx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-gcXYltjl4P30rKqQ6L_kKmA2J5Z9rb0',
    appId: '1:16690528086:ios:2e79bec8bd9ea865da20f7',
    messagingSenderId: '16690528086',
    projectId: 'totelx',
    storageBucket: 'totelx.appspot.com',
    iosBundleId: 'com.example.totelx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl8NTzw1BXEr1PVIju6LSWvkribc00ppY',
    appId: '1:16690528086:web:2852b87438a0715eda20f7',
    messagingSenderId: '16690528086',
    projectId: 'totelx',
    authDomain: 'totelx.firebaseapp.com',
    storageBucket: 'totelx.appspot.com',
  );
}
